services:
  db:
    image: postgres:latest
    container_name: todolist-db
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources:/docker-entrypoint-initdb.d

volumes:
  postgres_data: